services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    container_name: l0-zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok,stat,srvr,mntr"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: l0-kafka-1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/kafka/9092"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres:
    image: postgres:14
    container_name: l0-postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  app:
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:1234@postgres:5432/data?sslmode=disable
      DB_DSN: postgres://postgres:1234@postgres:5432/data?sslmode=disable
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: orders
      HTTP_ADDR: :8080

    volumes:
      - ./migrations:/app/migrations:ro

    command: >
      sh -c "goose -dir=/app/migrations up && exec /app/app"

    restart: on-failure

  producer:
    build:
      context: .
      dockerfile: ./cmd/producer/Dockerfile
    container_name: l0-producer
    depends_on:
      kafka:
        condition: service_healthy
    restart: always

  app-migrate-up:
    image: l0-app
    depends_on:
      postgres:
        condition: service_healthy
    command: goose -dir=/app/migrations postgres "$DB_DSN" up

  app-migrate-down:
    image: l0-app
    depends_on:
      postgres:
        condition: service_healthy
    command: goose -dir=/app/migrations postgres "$DB_DSN" down

  app-migrate-status:
    image: l0-app
    depends_on:
      postgres:
        condition: service_healthy
    command: goose -dir=/app/migrations postgres "$DB_DSN" status

